# Generated by Django 6.0.3 on 2026-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assignment_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='event_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='finished_assignment_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='finished_event_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='finished_normal_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='finished_project_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='normal_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_task',
            field=models.IntegerField(default=0),
        ),
    ]
