# Generated by Django 6.0.3 on 2026-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch_of',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='part_of',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_branch_of',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
