# Generated by Django 6.0.3 on 2026-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_branch_of_event_part_of_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('event', 'Event'), ('assignment', 'Assignment'), ('project', 'Project')], default='normal', max_length=20),
        ),
    ]
