# Generated by Django 6.0.3 on 2026-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('restricted', 'Restricted')], default='locked', max_length=25)),
                ('profile_req', models.IntegerField(default=0)),
                ('project_req', models.TextField(max_length=255)),
                ('finish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
