# Generated by Django 6.0.3 on 2026-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
