# Generated by Django 6.0.3 on 2026-04-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_image_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='projects_project',
        ),
    ]
