# Generated by Django 6.0.3 on 2026-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_req',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
