# Generated by Django 6.0.3 on 2026-03-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(default='Beginner', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('copper_coin', models.IntegerField(default=0)),
                ('bronze_coin', models.IntegerField(default=0)),
                ('silver_coin', models.IntegerField(default=0)),
                ('gold_coin', models.IntegerField(default=0)),
                ('platinum_coin', models.IntegerField(default=0)),
                ('titanium_coin', models.IntegerField(default=0)),
                ('mithril_coin', models.IntegerField(default=0)),
                ('dragon_coin', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
