# Generated by Django 6.0.3 on 2026-03-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_assignment_task_profile_event_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assignment_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='event_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finished_assignment_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finished_event_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finished_normal_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='finished_project_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='normal_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_task',
        ),
    ]
