# Generated by Django 6.0.3 on 2026-04-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_courses_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='project',
        ),
    ]
