# Generated by Django 6.0.3 on 2026-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
