# Generated by Django 6.0.3 on 2026-04-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_has_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='branch_of',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='part_of',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sub_branch_of',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='event',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('event', 'Event'), ('assignment', 'Assignment')], default='normal', max_length=20),
        ),
    ]
